name: 构建并推送容器镜像

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 登陆GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: 构建并推送镜像
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/comfyui-images
          docker build -t $IMAGE_NAME:matpool-dev-202506  -f matpool-dev-202506/Dockerfile  ./matpool-dev-202506
          docker push $IMAGE_NAME:matpool-dev-202506