name: 构建并推送容器镜像

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 登陆GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: 登陆阿里云镜像仓库
        run: echo "${{ secrets.ALIYUN_CR_PASSWD }}" | docker login registry.cn-hangzhou.aliyuncs.com -u ${{ secrets.ALIYUN_CR_USER }} --password-stdin
      - name: 构建镜像
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/comfyui-images
          docker build -t $IMAGE_NAME:matpool-a100-40g-dev  -f matpool-a100-40g/Dockerfile  ./matpool-a100-40g
          docker tag $IMAGE_NAME:matpool-a100-40g-dev ${{ secrets.ALIYUN_CR_URI }}:a100-40g-dev
      - name: 推送镜像到阿里云
        run: |
          docker push ${{ secrets.ALIYUN_CR_URI }}:a100-40g-dev
      - name: 推送镜像到ghcr
        run: |
          docker push $IMAGE_NAME:matpool-a100-40g-dev

